# Generated by Django 4.2.4 on 2023-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
