# Generated by Django 4.2.4 on 2023-11-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientcare', '0002_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
