# Generated by Django 4.2.4 on 2023-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientcare', '0004_alter_log_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
