# Generated by Django 4.2.4 on 2023-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientcare', '0006_alter_log_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
