# Generated by Django 4.2.4 on 2023-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientcare', '0008_auditentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
